HTTP/2 429 
server: daiquiri/5
content-type: text/html
retry-after: 30
strict-transport-security: max-age=31536000; includeSubDomains
x-apple-jingle-correlation-key: 3KXBKQCMVZYMWTHAFAOBIAB2Q4
x-daiquiri-instance: daiquiri:12282006:mr47p00it-qujn05121902:7987:26RELEASE153:daiquiri-amp-store-l7shared-ext-001-mr
x-daiquiri-debug-worker-pid: 114774
content-length: 73
date: Sun, 13 Sep 2026 17:22:30 GMT
x-cache: TCP_MISS from a2-20-196-208.deploy.akamaitechnologies.com (AkamaiGHost/22.6.3-da071da6976b6d633b0b37bcfe65c0fc) (-)
x-true-cache-key: /L/itunes.apple.com/search vcd=2897 ci2=country=de&entity=software&limit=1&term=rl43///
x-cache-remote: TCP_MISS from a23-36-160-155.deploy.akamaitechnologies.com (AkamaiGHost/22.6.3-da071da6976b6d633b0b37bcfe65c0fc) (-)
x-apple-partner: origin.0

Rate limit has been exceeded for: itunes-apple-com|general|203.0.113.10
